### ISSUE TITLE
Ability to disable the process.exit() behaviour in the convenience main() function

### ISSUE THREAD

**Issue by orospakr** [trentm/node-cmdln#11]
In my app, I don't drive my main behaviour from my cmdln callback handlers, but rather I have them set up a config object as well as a queue of commands to execute, and I had it processing that queue of items once cmdln.main() returned control (which it no longer does).

Thank you!

**Comment by orospakr** [comment]
For now I'm just stubbing out `process.exit` in my code, which is a nasty hack to avoid a fork. ;)

**Comment by trentm** [comment]
Sorry for not having responded earlier. I guess you'd want a callback when cmdln.main is complete then?

**Comment by trentm** [comment]
publised in cmdln@4.1.0
