### ISSUE TITLE
cmdln with ES6 classes

### ISSUE THREAD

**Issue by terinjokes** [trentm/node-cmdln#14]
With ES6 Class syntax, items added to a class's prototype are described as being non-enumerable. This is defined in [§14.3.9](https://tc39.github.io/ecma262/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation) which is called by [§14.5.3 (21).a.i and (21).b.i](https://tc39.github.io/ecma262/#sec-runtime-semantics-classdefinitionevaluation), and is simplified in the [`es-class` documentation](https://github.com/WebReflection/es-class/blob/master/FEATURES.md#prototype).

Subcommands are currently found by looping over the extended Cmdln class's prototype looking for functions that match `do_*`. When using ES6 class syntax (or backport) these functions would be skipped due to their non-enumerable status.

While the old way is certainly still valid, is there plan to move cmdln forward to support ES6 classes?

**Comment by davepacheco** [comment]
Thanks for the heads-up, but there's no plan to rewrite cmdln for ES6.

**Comment by MaThGo** [comment]
I know this issue is almos a year old, but I'd really like to keep using cmdln and that won't be possible anymore unless it'll work with ES6 Classes.

May I ask why there are no plans to make cmdln ES6 compatible?
Would you at least accept a PR with the necessary changes?
