### ISSUE TITLE
Allow removal of Options header in Help

### ISSUE THREAD

**Issue by meanjoe45** [trentm/node-cmdln#19]
When constructing the help menu and the `{{options}}` template variable is used, the header `Options:` is automatically attached to the output. Is it possible to remove this header or make it configurable? My help menu uses a heavy all caps header style (eg **`OPTIONS`**) that does not match the automatically attached header.

Thanks.

**Comment by trentm** [comment]
@meanjoe45 Thanks for the issue. ... almost a full year later I got back to doing a small amount of work on this module. I've added a facility for this and published as cmdln@5.1.0 should you happen to still be using this. Cheers.

See https://github.com/trentm/node-cmdln/blob/master/CHANGES.md#510
